from enum import Enum


class ErrorCode(str, Enum):
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_TAKEN = "EMAIL_TAKEN"

    S3_UNAUTHORIZED = "S3_UNAUTHORIZED"
    S3_BUCKET_NOT_FOUND = "S3_BUCKET_NOT_FOUND"
    
    MEDIA_TYPE_NOT_SUPPORTED = "MEDIA_TYPE_NOT_SUPPORTED"
    MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND"


    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_MEDIA_LIMIT = "PRODUCT_MEDIA_LIMIT"
    INVALID_PRICE_VALUE = "INVALID_PRICE_VALUE"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
